const { _electron } = require('playwright');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const assert = require('node:assert/strict');
const version = require('../package.json').version;
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'pet-controls-'));
const executablePath = require('electron');
const launch = () => _electron.launch({ executablePath, args: [path.join(__dirname, 'controls-boot.cjs')], env: { ...process.env, PET_CONTROLS_PROFILE: profile }, timeout: 15000 });

(async () => {
  let app;
  try {
    app = await launch();
    console.log('Electron attached');
    app.process().stderr.on('data', (data) => process.stderr.write(data));
    const pet = await app.firstWindow({ timeout: 15000 });
    await pet.waitForFunction(() => document.querySelector('video')?.currentTime > 0);
    assert.equal(await app.evaluate(() => !!global.petProbe.menu.getMenuItemById('settings')), true, '系統匣應有設定入口');
    const opened = app.waitForEvent('window');
    await app.evaluate(() => global.petProbe.menu.getMenuItemById('settings').click());
    const settings = await opened;
    await settings.waitForFunction(() => !!window.settingsAPI);
    const initial = await settings.evaluate(() => window.settingsAPI.getState());
    assert.equal(initial.pets.length, 1);
    console.log('DISPLAYS', JSON.stringify(initial.displays));
    await settings.locator('#pet-form').waitFor({ state: 'visible' });
    await settings.screenshot({ path: path.join(__dirname, 'output', `v${version}-settings.png`) });
    const id = initial.pets[0].id;
    await settings.evaluate((id) => window.settingsAPI.updatePet(id, { size: 150, roaming: false }), id);
    await pet.waitForFunction(() => window.innerWidth === 630);
    const native = await app.browserWindow(pet);
    const nativeId = await native.evaluate((win) => win.id);
    const contentId = await native.evaluate((win) => win.webContents.id);
    await settings.evaluate((id) => window.settingsAPI.updatePet(id, { alwaysOnTop: false, roamingRange: { left: 20, right: 80 } }), id);
    assert.equal(await native.evaluate((win) => win.isAlwaysOnTop()), false, '設定應可關閉永遠置頂');
    await settings.evaluate((id) => window.settingsAPI.updatePet(id, { alwaysOnTop: true }), id);
    assert.equal(await native.evaluate((win) => win.isAlwaysOnTop()), true, '設定應可重新開啟永遠置頂');
    await pet.waitForFunction(() => !document.getElementById('pet-error').classList.contains('visible'));
    await new Promise((resolve) => setTimeout(resolve, 200));
    const maskInfo = await app.evaluate((_electron, contentId) => {
      const mask = global.petProbe.masks[contentId];
      return mask && { length: mask.alpha.length, opaque: mask.alpha.filter((alpha) => alpha > 16).length };
    }, contentId);
    assert.ok(maskInfo?.opaque > 500 && maskInfo.opaque < maskInfo.length / 2, '影片應提供透明背景與角色遮罩');
    let bounds = await native.evaluate((win) => win.getBounds());
    await app.evaluate((_e, bounds) => { global.petProbe.cursor = { x: bounds.x + 5, y: bounds.y + 5 }; }, bounds);
    await new Promise((resolve) => setTimeout(resolve, 80));
    assert.equal(await app.evaluate((_e, id) => global.petProbe.ignored[id], nativeId), true, '透明區域應開啟原生滑鼠穿透');
    const offset = { x: bounds.width / 2, y: bounds.height / 2 };
    await app.evaluate((_e, point) => { global.petProbe.cursor = point; }, { x: bounds.x + offset.x, y: bounds.y + offset.y });
    await new Promise((resolve) => setTimeout(resolve, 80));
    assert.equal(await app.evaluate((_e, id) => global.petProbe.ignored[id], nativeId), false, '角色身體應接收原生滑鼠');
    await pet.evaluate(() => window.petAPI.beginDrag());
    await new Promise((resolve) => setTimeout(resolve, 50));
    const targetDisplay = initial.displays[1] || initial.displays[0];
    const target = { x: targetDisplay.workArea.x + 700, y: targetDisplay.workArea.y + 500 };
    await app.evaluate((_e, point) => { global.petProbe.cursor = point; }, target);
    await new Promise((resolve) => setTimeout(resolve, 120));
    bounds = await native.evaluate((win) => win.getBounds());
    assert.equal(bounds.x, target.x - offset.x, '主程序游標追蹤應跨過螢幕接縫');
    assert.equal(bounds.y, target.y - offset.y);
    await pet.evaluate(() => window.petAPI.endDrag(false));
    await new Promise((resolve) => setTimeout(resolve, 80));
    const moved = await settings.evaluate(() => window.settingsAPI.getState());
    assert.equal(moved.pets[0].displayId, targetDisplay.id);
    console.log('PASS real video alpha mask, native ignore-mouse toggling, DIP drag to display', targetDisplay.id);
    const added = await settings.evaluate(() => window.settingsAPI.addPet());
    assert.equal(added.pets.length, 2);
    await settings.evaluate((id) => window.settingsAPI.updatePet(id, { visible: false }), added.pets[1].id);
    await new Promise((resolve) => setTimeout(resolve, 300));
    const count = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().filter((win) => win.webContents.getURL().endsWith('/index.html') && win.isVisible()).length);
    assert.equal(count, 1, '尚未載入就隱藏的新桌寵不得在載入後自行顯示');
    await app.close();
    app = await launch();
    await app.firstWindow();
    const reopened = app.waitForEvent('window');
    await app.evaluate(() => global.petProbe.menu.getMenuItemById('settings').click());
    const restored = await reopened;
    await restored.waitForFunction(() => !!window.settingsAPI);
    const saved = await restored.evaluate(() => window.settingsAPI.getState());
    assert.equal(saved.pets.length, 2);
    assert.equal(saved.pets[0].size, 150);
    assert.equal(saved.pets[0].roaming, false);
    assert.deepEqual(saved.pets[0].roamingRange, { left: 20, right: 80 });
    assert.equal(saved.pets[0].alwaysOnTop, true);
    assert.equal(saved.pets[1].visible, false);
    console.log('PASS settings add/update/hide and restart persistence');
    for (const pet of saved.pets) await restored.evaluate((id) => window.settingsAPI.removePet(id), pet.id);
    await restored.locator('#empty-state').waitFor({ state: 'visible' });
    await restored.close();
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 0);
    assert.equal(await app.evaluate(() => global.petProbe.tray.isDestroyed()), false);
    const again = app.waitForEvent('window');
    await app.evaluate(() => global.petProbe.menu.getMenuItemById('settings').click());
    const emptySettings = await again;
    await emptySettings.waitForFunction(() => !!window.settingsAPI);
    const fromEmpty = await emptySettings.evaluate(() => window.settingsAPI.addPet());
    assert.equal(fromEmpty.pets.length, 1);
    console.log('PASS removing all pets keeps tray alive; settings can add again');
  } finally { if (app) await app.close(); fs.rmSync(profile, { recursive: true, force: true }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
